### ISSUE TITLE
Feature suggestion: onAfterTruncate callback

### ISSUE THREAD

**Issue by burtek** [parsable/react-truncate-markup#11]
Hi!

Just a quick suggestion: how about adding a callback (`onAfterTruncate` or sth) that would be fired after the text has been truncated? It could be helpful to recalculate dynamically positioned elements after the text is truncated...

**Comment by patrik-piskay** [comment]
There is an issue with this feature request that I hadn't realised until after I implemented it few days ago 😅 The issue is with how this feature is going to be used most of the times - `onAfterTruncate` will most probably call `setState` and this happens: the `onAfterTruncate` callback calls `this.setState` on the parent component, which will trigger rerender, which will trigger a new `<TruncateMarkup />` run, which, when finished, will trigger the `onAfterTruncate` callback, which will call `this.setState`, ... and we are in an infinite loop.

I can't see any obvious solution to this - I was thinking doing something like `shouldComponentUpdate` that would skip any rerender when the same markup (`children`) was provided - because that's what we need to do: realise we already truncated some input once and don't do it again. 

The issue with that is that `this.props.children` will always be different, even if it didn't change between 2 renders, because they won't be referentially equal. And even if we solved this by some subobtimal solution (I was thinking of some sort of a `children` deep equal algo, which would not work for any inlined function (e.g. used as event handlers)), it would never work for @samwalshnz's case, because he *does need* to change the children (add `title` after truncation). So even if we were checking if the `children` prop didn't change, in this case it _would change_ and we would rerender, retruncate, call `onAfterTruncate` again and we are in the infinite loop again.

Another solution @pooyaj came up with was to call the `onAfterTruncate` only once. On the first render we would truncate and call `onAfterTruncate`, which might call `setState` on the parent and cause a rerender of `<TruncateMarkup />`. It will rerender (and truncate the original again), but because it knows it already reported the previous run, it won't call the callback again. The only way to force it to call the callback would be to make React to remount `<TruncateMarkup />` by setting a different `key` prop on it. In other words, `onAfterTruncate` will only run on the initial mount, it won't run on any update. 

While obviously this is not ideal, it _could_ work well. Generally, there are 2 ways to trigger the update run: initiated by a change from the parent component (external), or because the target element was resized (internal).

If we consider that a legit external updates (meaning the `children` markup is really different between 2 renders) rarely happen (and the parent component probably knows about the change, so if it is interested in the callback being run again, it can just force the remount on it - **note:** _this whole proposal is about the `onAfterTruncate` callback only, any update will still continue to trigger the truncation run, it just won't be reported by the `onAfterTruncate` callback_), we are left with the internal update calls on element resize.

Luckily, this one could still be supported and we could still call `onAfterTruncate` on any update caused by the element's resize.

So bottomline, by this change we could still support most of the cases out-of-the-box, and for the rest (when some `children` markup change is necessary **and at the same time** a subsequent `onAfterTruncate` call is desired), the parent can set a different `key` on `<TruncateMarkup />`, forcing it to remount.

What are your thoughts @burtek @samwalshnz? Would this approach work for your cases?
