### ISSUE TITLE
Two lines truncation bug

### ISSUE THREAD

**Issue by gruzzilkin** [parsable/react-truncate-markup#2]
Hello! First of all, thanks for awesome component! 

And here is a demo of the bug: https://codesandbox.io/s/2zk3z45kqj.
![image](https://user-images.githubusercontent.com/47628/34124068-66c9c250-e453-11e7-8a29-2d4e73b02568.png)

Could you suggest some workaround?

**Comment by patrik-piskay** [comment]
The issue is caused by using blocks inside the `TruncateMarkup` component 
```
<div>Marcelya Salimzhanova street, 40, Kazan</div>
<div>metro Gabdulla Tukaya Square, Center</div>
```
Ideally you would not use blocks because if you specify that you want 2 lines like in your example, if the first `div` breaks into 2 lines, in the best case you'll end up with what your image shows (but ending with `Kazan...` - missing `n` - that might be fixable, will need to check as to how easy that would be) - because the second `div` would be on the 3rd line.

So ideally you would use inline elements - what is your use case for using blocks? What would be your expected result for the image above?

**Comment by gruzzilkin** [comment]
Thanks for quick reply! 

My case is simple. I need line break between address and metro by design :-)

**Comment by patrik-piskay** [comment]
Does it make sense to truncate both lines separately then?
```
<div>
  <TruncateMarkup lines={1}>
    <div>Marcelya Salimzhanova street, 40, Kazan</div>
  </TruncateMarkup>
  <TruncateMarkup lines={1}>
    <div>metro Gabdulla Tukaya Square, Center</div>
  </TruncateMarkup>
</div>
```

Because otherwise with
```
<TruncateMarkup lines={2}>
  <div>
    <div>Marcelya Salimzhanova street, 40, Kazan</div>
    <div>metro Gabdulla Tukaya Square, Center</div>
  </div>
</TruncateMarkup>
```
you are risking that when the first line needs to be broken into 2 lines, you are not going to show the metro part at all

But it would help to know what your expected result for https://codesandbox.io/s/2zk3z45kqj is :)

**Comment by gruzzilkin** [comment]
BTW, to trim a single line you need to use the css-only solutions ;-)

**Comment by SuperOleg39** [comment]
Hello!

Have same problem with react-truncate-markup v 4.0.0 and custom ellipsis

Example https://codesandbox.io/s/p2r01nr897

Look's like ellipsis width not counted in truncated text size

**Comment by patrik-piskay** [comment]
Hey @SuperOleg39, I see 2 issues there:

1 - `lines={4}` but it only displays 2 - that's because there is margin specified on `p` elements. So a single line in `p` (with 1em margin top and bottom) already takes as much space as 3 lines would normally take. If you set `margin: 0;` on `p` elements, you get 4 lines rendered.

I don't see any way to fix this so it works fine with paddings and margins on the inside elements. The current strategy is to calculate a single line height and the wrapper's height in pixels, and divide the wrapper's height by the single line height - this gives us an estimate of how many lines were rendered. We then compare this number to the number specified in the `lines` props. So if the wrapper's height is 80px and a single line height is 20px, we can fit 4 lines. but if there is margin/padding on any inside element set to 20px both top and bottom, it already takes as much space as 3 lines (20px margin top, 20px single line, 20px margin bottom).
So my recommendation is to either not use padding/margin on inside elements, or to bump up the `lines` prop value to accommodate the extra space needed by the padding/margin.

If I remove the margin on `p` elements in your example, this is what I get https://cl.ly/807c658fa97b - 4 lines rendered as requested.

2 - the ellipsis is rendered on a new line - I'll need to spend some time debugging this, will update you once I have more info

**Comment by patrik-piskay** [comment]
Hey @SuperOleg39, I see 2 issues there:

1 - `lines={4}` but it only displays 2 - that's because there is margin specified on `p` elements. So a single line in `p` (with 1em margin top and bottom) already takes as much space as 3 lines would normally take. If you set `margin: 0;` on `p` elements, you get 4 lines rendered.

I don't see any way to fix this so it works fine with paddings and margins on the inside elements. The current strategy is to calculate a single line height and the wrapper's height in pixels, and divide the wrapper's height by the single line height - this gives us an estimate of how many lines were rendered. We then compare this number to the number specified in the `lines` props. So if the wrapper's height is 80px and a single line height is 20px, we can fit 4 lines. but if there is margin/padding on any inside element set to 20px both top and bottom, it already takes as much space as 3 lines (20px margin top, 20px single line, 20px margin bottom).
So my recommendation is to either not use padding/margin on inside elements, or to bump up the `lines` prop value to accommodate the extra space needed by the padding/margin.

If I remove the margin on `p` elements in your example, this is what I get https://cl.ly/807c658fa97b - 4 lines rendered as requested.

2 - the ellipsis is rendered on a new line - I'll need to spend some time debugging this, will update you once I have more info

**Comment by patrik-piskay** [comment]
Hey @SuperOleg39, I see 2 issues there:

1 - `lines={4}` but it only displays 2 - that's because there is margin specified on `p` elements. So a single line in `p` (with 1em margin top and bottom) already takes as much space as 3 lines would normally take. If you set `margin: 0;` on `p` elements, you get 4 lines rendered.

I don't see any way to fix this so it works fine with paddings and margins on the inside elements. The current strategy is to calculate a single line height and the wrapper's height in pixels, and divide the wrapper's height by the single line height - this gives us an estimate of how many lines were rendered. We then compare this number to the number specified in the `lines` props. So if the wrapper's height is 80px and a single line height is 20px, we can fit 4 lines. but if there is margin/padding on any inside element set to 20px both top and bottom, it already takes as much space as 3 lines (20px margin top, 20px single line, 20px margin bottom).
So my recommendation is to either not use padding/margin on inside elements, or to bump up the `lines` prop value to accommodate the extra space needed by the padding/margin.

If I remove the margin on `p` elements in your example, this is what I get https://cl.ly/807c658fa97b - 4 lines rendered as requested.

2 - the ellipsis is rendered on a new line - I'll need to spend some time debugging this, will update you once I have more info

**Comment by SuperOleg39** [comment]
Thx for fast answer!

**Comment by stropho** [comment]
> 2 - the ellipsis is rendered on a new line - I'll need to spend some time debugging this, will update you once I have more info

I had a similar issue. The **short answer** is that 2 lines don't fit, but 1 line + line of ellipses do.

In the sandbox example ( https://codesandbox.io/s/p2r01nr897 ) : 

- line height inside `<p/>`: 18px
- 4 lines expected height: 72px
- `<p/>` with margin: 50px
- ellipses line height: 19px

1 line with `<p/>` + line of ellipses:  50 + 19 = 69px
**69 < 72**
2 lines with `<p/>`: 100px
**100 > 72**

**Comment by patrik-piskay** [comment]
Ah, thanks @stropho! so it's the same source then

**Comment by girish-vadhel** [comment]
I am using react-truncate-markup v 4.1.0, the ellipsis is rendered on a new line in same example https://codesandbox.io/s/p2r01nr897 even if i remove margin applied to paragraph tag

It works fine if i remove the paragraph tag else it wont display text in last line
