### ISSUE TITLE
truncate seems to be lagging behind the size of the box

### ISSUE THREAD

**Issue by SeanYHe** [parsable/react-truncate-markup#26]
[Reproducable in `onTruncate callback` case from the README](https://react-truncate-markup-guzutnrduf.now.sh/#onTruncate-callback)

When shrinking the box, text goes to the second line even though `lines={1}` was passed into the props.
![image](https://user-images.githubusercontent.com/17264975/56391457-ae927f00-61fc-11e9-9e15-9045487a454d.png)

When expanding, text is truncated even though there is enough room.
![image](https://user-images.githubusercontent.com/17264975/56391419-94f13780-61fc-11e9-9415-6f34a9720557.png)

Seems like something to do with the `setState` called in `onTruncate`, when I removed it things were fine.

**Comment by patrik-piskay** [comment]
Hey @yuxuansean1, if you are referring to what you can see here https://cl.ly/3ae9f8d1f164 - meaning the screenshot you took is just a temporary state before RTM updates it again, then you are correct. 

RTM by itself does a few `setState`s in order to find the longest "substring" that still fits the container, but it still works fine and you don't notice any lag when rendering something once (most cases probably). 

What happens here when resizing is that RTM does its thing on every resize event which is a lot of setStates, plus, as you mentioned, the `onTruncate` callback sets state as well. So I think it's reasonable to expect when resizing the box and then setting state based on the RTM result, that there will be some lag. But it's just a demo case - I've added the resize box to the examples just to demonstrate how the callback functionality works, but I don't expect that setup to be used in real apps.

**Comment by yuxuansean1** [comment]
Hi @patrik-piskay, thanks for your response.

The issue i'm seeing is that those screenshots are not a temporary state, they are what is displayed after the resize has finished.
![Apr-22-2019 10-55-13](https://user-images.githubusercontent.com/17264975/56506676-3b835400-64ed-11e9-9837-59513f57a995.gif)

**Comment by patrik-piskay** [comment]
Interesting! what browser is that? Can you verify that it happens in other browsers as well?

**Comment by yuxuansean1** [comment]
This was on Chrome, I reproduced this in Firefox, Edge and Safari as well.
