### ISSUE TITLE
Does not render into jsdom

### ISSUE THREAD

**Issue by tylerthehaas** [parsable/react-truncate-markup#37]
**Describe the bug**
This does not run in a test environment. Either get an error saying `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'` or it just doesn't render anything into jsdom.

**To Reproduce**
https://codesandbox.io/s/icy-tree-rr3dq

**Comment by patrik-piskay** [comment]
Hi, RTM relies on browser APIs to work. in this specific case (`getComputedStyle`) you're seeing this error because of its dependency (`line-height` package), but it's not only that, RTM relies on actually rendering the content to an HTML box and measurements. even if you mock `line-height` lib it'll probably won't have the same effect as in a real app. because of that I suggest you mock RTM itself for your unit tests. For E2E browser tests you won't have any issues, with real world results as well.
